// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_stage5_clear = "CgkIxLi5xPYJEAIQBQ"; // <GPGSID>
        public const string achievement_box = "CgkIxLi5xPYJEAIQDA"; // <GPGSID>
        public const string achievement_stater = "CgkIxLi5xPYJEAIQAQ"; // <GPGSID>
        public const string achievement_stage1_clear = "CgkIxLi5xPYJEAIQAw"; // <GPGSID>
        public const string achievement_playcount = "CgkIxLi5xPYJEAIQCQ"; // <GPGSID>
        public const string achievement_gold = "CgkIxLi5xPYJEAIQCg"; // <GPGSID>
        public const string achievement_upgrade = "CgkIxLi5xPYJEAIQDg"; // <GPGSID>
        public const string leaderboard_sumsumzombie_leaderboard = "CgkIxLi5xPYJEAIQAA"; // <GPGSID>
        public const string achievement_stage_7_clear = "CgkIxLi5xPYJEAIQBg"; // <GPGSID>
        public const string achievement_stage2_clear = "CgkIxLi5xPYJEAIQBA"; // <GPGSID>
        public const string achievement_stage_10_clear = "CgkIxLi5xPYJEAIQBw"; // <GPGSID>
        public const string achievement_boxopen = "CgkIxLi5xPYJEAIQDQ"; // <GPGSID>
        public const string achievement_playtime = "CgkIxLi5xPYJEAIQCA"; // <GPGSID>
        public const string achievement_potion = "CgkIxLi5xPYJEAIQCw"; // <GPGSID>

}

