public enum STATINDEX
{
    _00MAXHP,
    _01DECELERATIONHP,
    _02DEFENSE,
    _03GAINHP,
    _04GAINPOINT,
    _05GAINMONEY,
    _06STARTBONUS,
    _07SKILLBODYRATIO,
    _08SKILLDURATION,
    _09SKILLMAXCOUNT,
    _10INSTANTSTARTBONUS,
    _11INSTANTGAINMONEY,
    _12INSTANTGAINMAXHP,
    _13INSTANTSKILLMAXCOUNT,
    _14INSTANTGAINHP,
    MAX
}

public enum InvenIndex
{
    NONE,
    GOLD,
    MAX
}